// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.1
// source: playground/protobuf/common/filters/filters.proto

package filters

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Equals struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Equals string `protobuf:"bytes,1,opt,name=equals,proto3" json:"equals,omitempty"`
}

func (x *Equals) Reset() {
	*x = Equals{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playground_protobuf_common_filters_filters_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Equals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Equals) ProtoMessage() {}

func (x *Equals) ProtoReflect() protoreflect.Message {
	mi := &file_playground_protobuf_common_filters_filters_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Equals.ProtoReflect.Descriptor instead.
func (*Equals) Descriptor() ([]byte, []int) {
	return file_playground_protobuf_common_filters_filters_proto_rawDescGZIP(), []int{0}
}

func (x *Equals) GetEquals() string {
	if x != nil {
		return x.Equals
	}
	return ""
}

type NotEquals struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NotEquals string `protobuf:"bytes,1,opt,name=not_equals,json=notEquals,proto3" json:"not_equals,omitempty"`
}

func (x *NotEquals) Reset() {
	*x = NotEquals{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playground_protobuf_common_filters_filters_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotEquals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotEquals) ProtoMessage() {}

func (x *NotEquals) ProtoReflect() protoreflect.Message {
	mi := &file_playground_protobuf_common_filters_filters_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotEquals.ProtoReflect.Descriptor instead.
func (*NotEquals) Descriptor() ([]byte, []int) {
	return file_playground_protobuf_common_filters_filters_proto_rawDescGZIP(), []int{1}
}

func (x *NotEquals) GetNotEquals() string {
	if x != nil {
		return x.NotEquals
	}
	return ""
}

type In struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	In []string `protobuf:"bytes,1,rep,name=in,proto3" json:"in,omitempty"`
}

func (x *In) Reset() {
	*x = In{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playground_protobuf_common_filters_filters_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *In) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*In) ProtoMessage() {}

func (x *In) ProtoReflect() protoreflect.Message {
	mi := &file_playground_protobuf_common_filters_filters_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use In.ProtoReflect.Descriptor instead.
func (*In) Descriptor() ([]byte, []int) {
	return file_playground_protobuf_common_filters_filters_proto_rawDescGZIP(), []int{2}
}

func (x *In) GetIn() []string {
	if x != nil {
		return x.In
	}
	return nil
}

type LooseIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LooseIn []string `protobuf:"bytes,1,rep,name=loose_in,json=looseIn,proto3" json:"loose_in,omitempty"`
}

func (x *LooseIn) Reset() {
	*x = LooseIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playground_protobuf_common_filters_filters_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LooseIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LooseIn) ProtoMessage() {}

func (x *LooseIn) ProtoReflect() protoreflect.Message {
	mi := &file_playground_protobuf_common_filters_filters_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LooseIn.ProtoReflect.Descriptor instead.
func (*LooseIn) Descriptor() ([]byte, []int) {
	return file_playground_protobuf_common_filters_filters_proto_rawDescGZIP(), []int{3}
}

func (x *LooseIn) GetLooseIn() []string {
	if x != nil {
		return x.LooseIn
	}
	return nil
}

type NotIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NotIn []string `protobuf:"bytes,1,rep,name=not_in,json=notIn,proto3" json:"not_in,omitempty"`
}

func (x *NotIn) Reset() {
	*x = NotIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playground_protobuf_common_filters_filters_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotIn) ProtoMessage() {}

func (x *NotIn) ProtoReflect() protoreflect.Message {
	mi := &file_playground_protobuf_common_filters_filters_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotIn.ProtoReflect.Descriptor instead.
func (*NotIn) Descriptor() ([]byte, []int) {
	return file_playground_protobuf_common_filters_filters_proto_rawDescGZIP(), []int{4}
}

func (x *NotIn) GetNotIn() []string {
	if x != nil {
		return x.NotIn
	}
	return nil
}

type Contains struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Contains []string `protobuf:"bytes,1,rep,name=contains,proto3" json:"contains,omitempty"`
}

func (x *Contains) Reset() {
	*x = Contains{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playground_protobuf_common_filters_filters_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Contains) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contains) ProtoMessage() {}

func (x *Contains) ProtoReflect() protoreflect.Message {
	mi := &file_playground_protobuf_common_filters_filters_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contains.ProtoReflect.Descriptor instead.
func (*Contains) Descriptor() ([]byte, []int) {
	return file_playground_protobuf_common_filters_filters_proto_rawDescGZIP(), []int{5}
}

func (x *Contains) GetContains() []string {
	if x != nil {
		return x.Contains
	}
	return nil
}

type NotContains struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NotContains []string `protobuf:"bytes,1,rep,name=not_contains,json=notContains,proto3" json:"not_contains,omitempty"`
}

func (x *NotContains) Reset() {
	*x = NotContains{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playground_protobuf_common_filters_filters_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotContains) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotContains) ProtoMessage() {}

func (x *NotContains) ProtoReflect() protoreflect.Message {
	mi := &file_playground_protobuf_common_filters_filters_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotContains.ProtoReflect.Descriptor instead.
func (*NotContains) Descriptor() ([]byte, []int) {
	return file_playground_protobuf_common_filters_filters_proto_rawDescGZIP(), []int{6}
}

func (x *NotContains) GetNotContains() []string {
	if x != nil {
		return x.NotContains
	}
	return nil
}

type Equality struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to SealedValueOptional:
	//
	//	*Equality_Equals
	//	*Equality_NotEquals
	//	*Equality_In
	//	*Equality_NotIn
	//	*Equality_Contains
	//	*Equality_NotContains
	//	*Equality_LooseIn
	SealedValueOptional isEquality_SealedValueOptional `protobuf_oneof:"sealed_value_optional"`
}

func (x *Equality) Reset() {
	*x = Equality{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playground_protobuf_common_filters_filters_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Equality) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Equality) ProtoMessage() {}

func (x *Equality) ProtoReflect() protoreflect.Message {
	mi := &file_playground_protobuf_common_filters_filters_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Equality.ProtoReflect.Descriptor instead.
func (*Equality) Descriptor() ([]byte, []int) {
	return file_playground_protobuf_common_filters_filters_proto_rawDescGZIP(), []int{7}
}

func (m *Equality) GetSealedValueOptional() isEquality_SealedValueOptional {
	if m != nil {
		return m.SealedValueOptional
	}
	return nil
}

func (x *Equality) GetEquals() *Equals {
	if x, ok := x.GetSealedValueOptional().(*Equality_Equals); ok {
		return x.Equals
	}
	return nil
}

func (x *Equality) GetNotEquals() *NotEquals {
	if x, ok := x.GetSealedValueOptional().(*Equality_NotEquals); ok {
		return x.NotEquals
	}
	return nil
}

func (x *Equality) GetIn() *In {
	if x, ok := x.GetSealedValueOptional().(*Equality_In); ok {
		return x.In
	}
	return nil
}

func (x *Equality) GetNotIn() *NotIn {
	if x, ok := x.GetSealedValueOptional().(*Equality_NotIn); ok {
		return x.NotIn
	}
	return nil
}

func (x *Equality) GetContains() *Contains {
	if x, ok := x.GetSealedValueOptional().(*Equality_Contains); ok {
		return x.Contains
	}
	return nil
}

func (x *Equality) GetNotContains() *NotContains {
	if x, ok := x.GetSealedValueOptional().(*Equality_NotContains); ok {
		return x.NotContains
	}
	return nil
}

func (x *Equality) GetLooseIn() *LooseIn {
	if x, ok := x.GetSealedValueOptional().(*Equality_LooseIn); ok {
		return x.LooseIn
	}
	return nil
}

type isEquality_SealedValueOptional interface {
	isEquality_SealedValueOptional()
}

type Equality_Equals struct {
	Equals *Equals `protobuf:"bytes,1,opt,name=equals,proto3,oneof"`
}

type Equality_NotEquals struct {
	NotEquals *NotEquals `protobuf:"bytes,2,opt,name=not_equals,json=notEquals,proto3,oneof"`
}

type Equality_In struct {
	In *In `protobuf:"bytes,3,opt,name=in,proto3,oneof"`
}

type Equality_NotIn struct {
	NotIn *NotIn `protobuf:"bytes,4,opt,name=not_in,json=notIn,proto3,oneof"`
}

type Equality_Contains struct {
	Contains *Contains `protobuf:"bytes,5,opt,name=contains,proto3,oneof"`
}

type Equality_NotContains struct {
	NotContains *NotContains `protobuf:"bytes,6,opt,name=not_contains,json=notContains,proto3,oneof"`
}

type Equality_LooseIn struct {
	LooseIn *LooseIn `protobuf:"bytes,7,opt,name=loose_in,json=looseIn,proto3,oneof"`
}

func (*Equality_Equals) isEquality_SealedValueOptional() {}

func (*Equality_NotEquals) isEquality_SealedValueOptional() {}

func (*Equality_In) isEquality_SealedValueOptional() {}

func (*Equality_NotIn) isEquality_SealedValueOptional() {}

func (*Equality_Contains) isEquality_SealedValueOptional() {}

func (*Equality_NotContains) isEquality_SealedValueOptional() {}

func (*Equality_LooseIn) isEquality_SealedValueOptional() {}

type Id struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Equality *Equality `protobuf:"bytes,1,opt,name=equality,proto3" json:"equality,omitempty"`
}

func (x *Id) Reset() {
	*x = Id{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playground_protobuf_common_filters_filters_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_playground_protobuf_common_filters_filters_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_playground_protobuf_common_filters_filters_proto_rawDescGZIP(), []int{8}
}

func (x *Id) GetEquality() *Equality {
	if x != nil {
		return x.Equality
	}
	return nil
}

type Name struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Equality *Equality `protobuf:"bytes,1,opt,name=equality,proto3" json:"equality,omitempty"`
}

func (x *Name) Reset() {
	*x = Name{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playground_protobuf_common_filters_filters_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Name) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Name) ProtoMessage() {}

func (x *Name) ProtoReflect() protoreflect.Message {
	mi := &file_playground_protobuf_common_filters_filters_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Name.ProtoReflect.Descriptor instead.
func (*Name) Descriptor() ([]byte, []int) {
	return file_playground_protobuf_common_filters_filters_proto_rawDescGZIP(), []int{9}
}

func (x *Name) GetEquality() *Equality {
	if x != nil {
		return x.Equality
	}
	return nil
}

type Description struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Equality *Equality `protobuf:"bytes,1,opt,name=equality,proto3" json:"equality,omitempty"`
}

func (x *Description) Reset() {
	*x = Description{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playground_protobuf_common_filters_filters_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Description) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Description) ProtoMessage() {}

func (x *Description) ProtoReflect() protoreflect.Message {
	mi := &file_playground_protobuf_common_filters_filters_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Description.ProtoReflect.Descriptor instead.
func (*Description) Descriptor() ([]byte, []int) {
	return file_playground_protobuf_common_filters_filters_proto_rawDescGZIP(), []int{10}
}

func (x *Description) GetEquality() *Equality {
	if x != nil {
		return x.Equality
	}
	return nil
}

type FieldFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to SealedValueOptional:
	//
	//	*FieldFilter_Id
	//	*FieldFilter_Name
	//	*FieldFilter_Description
	SealedValueOptional isFieldFilter_SealedValueOptional `protobuf_oneof:"sealed_value_optional"`
}

func (x *FieldFilter) Reset() {
	*x = FieldFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playground_protobuf_common_filters_filters_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldFilter) ProtoMessage() {}

func (x *FieldFilter) ProtoReflect() protoreflect.Message {
	mi := &file_playground_protobuf_common_filters_filters_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldFilter.ProtoReflect.Descriptor instead.
func (*FieldFilter) Descriptor() ([]byte, []int) {
	return file_playground_protobuf_common_filters_filters_proto_rawDescGZIP(), []int{11}
}

func (m *FieldFilter) GetSealedValueOptional() isFieldFilter_SealedValueOptional {
	if m != nil {
		return m.SealedValueOptional
	}
	return nil
}

func (x *FieldFilter) GetId() *Id {
	if x, ok := x.GetSealedValueOptional().(*FieldFilter_Id); ok {
		return x.Id
	}
	return nil
}

func (x *FieldFilter) GetName() *Name {
	if x, ok := x.GetSealedValueOptional().(*FieldFilter_Name); ok {
		return x.Name
	}
	return nil
}

func (x *FieldFilter) GetDescription() *Description {
	if x, ok := x.GetSealedValueOptional().(*FieldFilter_Description); ok {
		return x.Description
	}
	return nil
}

type isFieldFilter_SealedValueOptional interface {
	isFieldFilter_SealedValueOptional()
}

type FieldFilter_Id struct {
	Id *Id `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type FieldFilter_Name struct {
	Name *Name `protobuf:"bytes,2,opt,name=name,proto3,oneof"`
}

type FieldFilter_Description struct {
	Description *Description `protobuf:"bytes,3,opt,name=description,proto3,oneof"`
}

func (*FieldFilter_Id) isFieldFilter_SealedValueOptional() {}

func (*FieldFilter_Name) isFieldFilter_SealedValueOptional() {}

func (*FieldFilter_Description) isFieldFilter_SealedValueOptional() {}

type FieldFilterList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilterList []*FieldFilter `protobuf:"bytes,1,rep,name=filter_list,json=filterList,proto3" json:"filter_list,omitempty"`
}

func (x *FieldFilterList) Reset() {
	*x = FieldFilterList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playground_protobuf_common_filters_filters_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldFilterList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldFilterList) ProtoMessage() {}

func (x *FieldFilterList) ProtoReflect() protoreflect.Message {
	mi := &file_playground_protobuf_common_filters_filters_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldFilterList.ProtoReflect.Descriptor instead.
func (*FieldFilterList) Descriptor() ([]byte, []int) {
	return file_playground_protobuf_common_filters_filters_proto_rawDescGZIP(), []int{12}
}

func (x *FieldFilterList) GetFilterList() []*FieldFilter {
	if x != nil {
		return x.FilterList
	}
	return nil
}

var File_playground_protobuf_common_filters_filters_proto protoreflect.FileDescriptor

var file_playground_protobuf_common_filters_filters_proto_rawDesc = []byte{
	0x0a, 0x30, 0x70, 0x6c, 0x61, 0x79, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x73, 0x2f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x22, 0x70, 0x6c, 0x61, 0x79, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x22, 0x20, 0x0a, 0x06, 0x45, 0x71, 0x75, 0x61, 0x6c, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x65, 0x71, 0x75, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x65, 0x71, 0x75, 0x61, 0x6c, 0x73, 0x22, 0x2a, 0x0a, 0x09, 0x4e, 0x6f, 0x74, 0x45,
	0x71, 0x75, 0x61, 0x6c, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x6f, 0x74, 0x5f, 0x65, 0x71, 0x75,
	0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x6f, 0x74, 0x45, 0x71,
	0x75, 0x61, 0x6c, 0x73, 0x22, 0x14, 0x0a, 0x02, 0x49, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x6e,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x02, 0x69, 0x6e, 0x22, 0x24, 0x0a, 0x07, 0x4c, 0x6f,
	0x6f, 0x73, 0x65, 0x49, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x6f, 0x6f, 0x73, 0x65, 0x5f, 0x69,
	0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x6f, 0x73, 0x65, 0x49, 0x6e,
	0x22, 0x1e, 0x0a, 0x05, 0x4e, 0x6f, 0x74, 0x49, 0x6e, 0x12, 0x15, 0x0a, 0x06, 0x6e, 0x6f, 0x74,
	0x5f, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x6f, 0x74, 0x49, 0x6e,
	0x22, 0x26, 0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x73, 0x22, 0x30, 0x0a, 0x0b, 0x4e, 0x6f, 0x74, 0x43,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x6f, 0x74, 0x5f, 0x63,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x6e,
	0x6f, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x73, 0x22, 0xa3, 0x04, 0x0a, 0x08, 0x45,
	0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x44, 0x0a, 0x06, 0x65, 0x71, 0x75, 0x61, 0x6c,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x67, 0x72,
	0x6f, 0x75, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x45, 0x71, 0x75,
	0x61, 0x6c, 0x73, 0x48, 0x00, 0x52, 0x06, 0x65, 0x71, 0x75, 0x61, 0x6c, 0x73, 0x12, 0x4e, 0x0a,
	0x0a, 0x6e, 0x6f, 0x74, 0x5f, 0x65, 0x71, 0x75, 0x61, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x2d, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x4e, 0x6f, 0x74, 0x45, 0x71, 0x75, 0x61, 0x6c, 0x73,
	0x48, 0x00, 0x52, 0x09, 0x6e, 0x6f, 0x74, 0x45, 0x71, 0x75, 0x61, 0x6c, 0x73, 0x12, 0x38, 0x0a,
	0x02, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x70, 0x6c, 0x61, 0x79,
	0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x49,
	0x6e, 0x48, 0x00, 0x52, 0x02, 0x69, 0x6e, 0x12, 0x42, 0x0a, 0x06, 0x6e, 0x6f, 0x74, 0x5f, 0x69,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x67, 0x72,
	0x6f, 0x75, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x4e, 0x6f, 0x74,
	0x49, 0x6e, 0x48, 0x00, 0x52, 0x05, 0x6e, 0x6f, 0x74, 0x49, 0x6e, 0x12, 0x4a, 0x0a, 0x08, 0x63,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e,
	0x70, 0x6c, 0x61, 0x79, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x73, 0x48, 0x00, 0x52, 0x08, 0x63,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x73, 0x12, 0x54, 0x0a, 0x0c, 0x6e, 0x6f, 0x74, 0x5f, 0x63,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e,
	0x70, 0x6c, 0x61, 0x79, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x73, 0x2e, 0x4e, 0x6f, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x73, 0x48, 0x00,
	0x52, 0x0b, 0x6e, 0x6f, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x73, 0x12, 0x48, 0x0a,
	0x08, 0x6c, 0x6f, 0x6f, 0x73, 0x65, 0x5f, 0x69, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2b, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x73, 0x2e, 0x4c, 0x6f, 0x6f, 0x73, 0x65, 0x49, 0x6e, 0x48, 0x00, 0x52, 0x07,
	0x6c, 0x6f, 0x6f, 0x73, 0x65, 0x49, 0x6e, 0x42, 0x17, 0x0a, 0x15, 0x73, 0x65, 0x61, 0x6c, 0x65,
	0x64, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c,
	0x22, 0x4e, 0x0a, 0x02, 0x49, 0x64, 0x12, 0x48, 0x0a, 0x08, 0x65, 0x71, 0x75, 0x61, 0x6c, 0x69,
	0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x67,
	0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x45, 0x71,
	0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x08, 0x65, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79,
	0x22, 0x50, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x48, 0x0a, 0x08, 0x65, 0x71, 0x75, 0x61,
	0x6c, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x70, 0x6c, 0x61,
	0x79, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e,
	0x45, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x08, 0x65, 0x71, 0x75, 0x61, 0x6c, 0x69,
	0x74, 0x79, 0x22, 0x57, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x48, 0x0a, 0x08, 0x65, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x45, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74,
	0x79, 0x52, 0x08, 0x65, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x22, 0xf5, 0x01, 0x0a, 0x0b,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x67, 0x72,
	0x6f, 0x75, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x49, 0x64, 0x48,
	0x00, 0x52, 0x02, 0x69, 0x64, 0x12, 0x3e, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x48, 0x00, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x53, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x70, 0x6c, 0x61,
	0x79, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e,
	0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x17, 0x0a, 0x15, 0x73, 0x65,
	0x61, 0x6c, 0x65, 0x64, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x6c, 0x22, 0x63, 0x0a, 0x0f, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x50, 0x0a, 0x0b, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x70, 0x6c,
	0x61, 0x79, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73,
	0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x0a, 0x66, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x70, 0x0a, 0x22, 0x70, 0x6c, 0x61, 0x79,
	0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x5a, 0x4a,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6d, 0x61, 0x72, 0x74,
	0x2d, 0x70, 0x6c, 0x61, 0x79, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x6c, 0x61, 0x79, 0x67, 0x72, 0x6f, 0x75,
	0x6e, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_playground_protobuf_common_filters_filters_proto_rawDescOnce sync.Once
	file_playground_protobuf_common_filters_filters_proto_rawDescData = file_playground_protobuf_common_filters_filters_proto_rawDesc
)

func file_playground_protobuf_common_filters_filters_proto_rawDescGZIP() []byte {
	file_playground_protobuf_common_filters_filters_proto_rawDescOnce.Do(func() {
		file_playground_protobuf_common_filters_filters_proto_rawDescData = protoimpl.X.CompressGZIP(file_playground_protobuf_common_filters_filters_proto_rawDescData)
	})
	return file_playground_protobuf_common_filters_filters_proto_rawDescData
}

var file_playground_protobuf_common_filters_filters_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_playground_protobuf_common_filters_filters_proto_goTypes = []interface{}{
	(*Equals)(nil),          // 0: playground.protobuf.common.filters.Equals
	(*NotEquals)(nil),       // 1: playground.protobuf.common.filters.NotEquals
	(*In)(nil),              // 2: playground.protobuf.common.filters.In
	(*LooseIn)(nil),         // 3: playground.protobuf.common.filters.LooseIn
	(*NotIn)(nil),           // 4: playground.protobuf.common.filters.NotIn
	(*Contains)(nil),        // 5: playground.protobuf.common.filters.Contains
	(*NotContains)(nil),     // 6: playground.protobuf.common.filters.NotContains
	(*Equality)(nil),        // 7: playground.protobuf.common.filters.Equality
	(*Id)(nil),              // 8: playground.protobuf.common.filters.Id
	(*Name)(nil),            // 9: playground.protobuf.common.filters.Name
	(*Description)(nil),     // 10: playground.protobuf.common.filters.Description
	(*FieldFilter)(nil),     // 11: playground.protobuf.common.filters.FieldFilter
	(*FieldFilterList)(nil), // 12: playground.protobuf.common.filters.FieldFilterList
}
var file_playground_protobuf_common_filters_filters_proto_depIdxs = []int32{
	0,  // 0: playground.protobuf.common.filters.Equality.equals:type_name -> playground.protobuf.common.filters.Equals
	1,  // 1: playground.protobuf.common.filters.Equality.not_equals:type_name -> playground.protobuf.common.filters.NotEquals
	2,  // 2: playground.protobuf.common.filters.Equality.in:type_name -> playground.protobuf.common.filters.In
	4,  // 3: playground.protobuf.common.filters.Equality.not_in:type_name -> playground.protobuf.common.filters.NotIn
	5,  // 4: playground.protobuf.common.filters.Equality.contains:type_name -> playground.protobuf.common.filters.Contains
	6,  // 5: playground.protobuf.common.filters.Equality.not_contains:type_name -> playground.protobuf.common.filters.NotContains
	3,  // 6: playground.protobuf.common.filters.Equality.loose_in:type_name -> playground.protobuf.common.filters.LooseIn
	7,  // 7: playground.protobuf.common.filters.Id.equality:type_name -> playground.protobuf.common.filters.Equality
	7,  // 8: playground.protobuf.common.filters.Name.equality:type_name -> playground.protobuf.common.filters.Equality
	7,  // 9: playground.protobuf.common.filters.Description.equality:type_name -> playground.protobuf.common.filters.Equality
	8,  // 10: playground.protobuf.common.filters.FieldFilter.id:type_name -> playground.protobuf.common.filters.Id
	9,  // 11: playground.protobuf.common.filters.FieldFilter.name:type_name -> playground.protobuf.common.filters.Name
	10, // 12: playground.protobuf.common.filters.FieldFilter.description:type_name -> playground.protobuf.common.filters.Description
	11, // 13: playground.protobuf.common.filters.FieldFilterList.filter_list:type_name -> playground.protobuf.common.filters.FieldFilter
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_playground_protobuf_common_filters_filters_proto_init() }
func file_playground_protobuf_common_filters_filters_proto_init() {
	if File_playground_protobuf_common_filters_filters_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_playground_protobuf_common_filters_filters_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Equals); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_playground_protobuf_common_filters_filters_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotEquals); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_playground_protobuf_common_filters_filters_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*In); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_playground_protobuf_common_filters_filters_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LooseIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_playground_protobuf_common_filters_filters_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_playground_protobuf_common_filters_filters_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Contains); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_playground_protobuf_common_filters_filters_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotContains); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_playground_protobuf_common_filters_filters_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Equality); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_playground_protobuf_common_filters_filters_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Id); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_playground_protobuf_common_filters_filters_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Name); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_playground_protobuf_common_filters_filters_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Description); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_playground_protobuf_common_filters_filters_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_playground_protobuf_common_filters_filters_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldFilterList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_playground_protobuf_common_filters_filters_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*Equality_Equals)(nil),
		(*Equality_NotEquals)(nil),
		(*Equality_In)(nil),
		(*Equality_NotIn)(nil),
		(*Equality_Contains)(nil),
		(*Equality_NotContains)(nil),
		(*Equality_LooseIn)(nil),
	}
	file_playground_protobuf_common_filters_filters_proto_msgTypes[11].OneofWrappers = []interface{}{
		(*FieldFilter_Id)(nil),
		(*FieldFilter_Name)(nil),
		(*FieldFilter_Description)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_playground_protobuf_common_filters_filters_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_playground_protobuf_common_filters_filters_proto_goTypes,
		DependencyIndexes: file_playground_protobuf_common_filters_filters_proto_depIdxs,
		MessageInfos:      file_playground_protobuf_common_filters_filters_proto_msgTypes,
	}.Build()
	File_playground_protobuf_common_filters_filters_proto = out.File
	file_playground_protobuf_common_filters_filters_proto_rawDesc = nil
	file_playground_protobuf_common_filters_filters_proto_goTypes = nil
	file_playground_protobuf_common_filters_filters_proto_depIdxs = nil
}
